version: '2'
services:
    zookeeper:
        image: 'dockter/zookeeper:0.1'
        ports:
            - '2181:2181'
    zookeeper-client:
        image: 'dockter/zookeeper-client:0.1'
        stdin_open: true
        tty: true
        command: ["-server", "${ZOOKEEPER_HOST}:2181"]
        depends_on:
            - 'zookeeper'